import type { MessageContext } from "./types";

export type SimulationTemplate = {
  id: string;
  title: string;
  description: string;
  category: "is_kariyer" | "flort_iliski" | "aile_arkadas" | "para_pazarlik" | "zor_mesajlar";
  difficulty: "Kolay" | "Orta" | "Zor";
  context: MessageContext;
};

export const templates: SimulationTemplate[] = [
  {
    id: "patron-zam",
    title: "Patrondan Zam İsteme",
    description: "Sorumluluklarınız arttı ama maaşınız aynı kaldı. Köprüleri yakmadan zam isteyin.",
    category: "is_kariyer",
    difficulty: "Orta",
    context: {
      incomingMessage: "Son dönemdeki performansım ve artan sorumluluklarım hakkında görüşmek istiyorum.",
      otherPerson: "Patron",
      otherPersonPersonality: "Anlayışlı ve Mantıklı",
      difficultyReason: "Zam istemek / hakkımı savunmak",
      goal: "Zam almak",
      tone: "Yumuşak ama ciddi",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      fear: "gözden düşmek veya reddedilmek",
      otherPersonAttitude: "Savunmacı",
      previouslyDiscussed: "Hayır, ilk kez açılacak",
      redLine: "Sektör ortalamasının altında bir artışı kabul etmem",
    },
  },
  {
    id: "mesai-reddi",
    title: "Hafta Sonu Mesai Reddi",
    description: "Yöneticinizin son dakika ilettiği hafta sonu çalışma talebini profesyonelce geri çevirin.",
    category: "is_kariyer",
    difficulty: "Kolay",
    context: {
      incomingMessage: "Hafta sonu acil bir teslimat var, cumartesi günü ofise gelebilir misin?",
      otherPerson: "Yönetici / Müdür",
      otherPersonPersonality: "Yoğun ve Dikkatsiz",
      difficultyReason: "Fazla mesaiyi kibarca reddetmek",
      goal: "Profesyonelce reddetmek",
      tone: "Profesyonel ve kibar",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      fear: "isteksiz görünmek veya tepki çekmek",
      otherPersonAttitude: "Kaçamak",
      previouslyDiscussed: "Hayır, ilk kez açılacak",
      redLine: "Hafta sonu planımı iptal edemem",
    },
  },
  {
    id: "kira-artisi",
    title: "Kira Artışına İtiraz",
    description: "Ev sahibinin yasal sınırın çok üzerindeki fahiş kira artış talebine karşı sınırlarınızı çizin.",
    category: "para_pazarlik",
    difficulty: "Zor",
    context: {
      incomingMessage: "Biliyorsun piyasa uçtu. Kirayı iki katına çıkarmamız gerekiyor, ne dersin?",
      otherPerson: "Ev sahibi",
      otherPersonPersonality: "Para Göz ve Katı",
      difficultyReason: "Kira artışına itiraz etmek / anlaşmak",
      goal: "Sınır koymak",
      tone: "Sert ama saygılı",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Sadece saygılı kapatmak istiyorum",
      fear: "evden çıkarılmak veya kavga etmek",
      financialIssue: "Kira artışı",
      currentAmount: "15.000 TL",
      minAcceptableLevel: "Yasal sınır olan %65 artışın üstüne çıkamam",
      otherPersonAttitude: "Artışı kabul etmiyor",
      leverageOrAlternative: "Banka ödeme dekontları ve yasal kira artış oranı",
      noAgreementAction: "Alternatif teklif sunarım",
    },
  },
  {
    id: "flort-netlik",
    title: "Flörte Netlik Sorusu",
    description: "Bir süredir belirsiz veya soğuk davranan flörtünüze hislerinizi ve durumu açın.",
    category: "flort_iliski",
    difficulty: "Orta",
    context: {
      incomingMessage: "İlişkimizin son dönemdeki soğukluğu ve iletişim belirsizliği hakkında konuşmak istiyorum.",
      otherPerson: "Flört",
      otherPersonPersonality: "Soğuk ve Mesafeli",
      difficultyReason: "İlişkiyi adlandırmak / netlik istemek",
      goal: "Niyetini anlamak",
      tone: "Samimi ve açık",
      replyLength: "Detaylı mesaj",
      preserveRelationship: "Evet",
      fear: "tamamen kopmak veya gurursuz görünmek",
      relationshipDuration: "Birkaç ay",
      otherPersonAttitude: "İlgili ama belirsiz",
      avoidAction: "Kendimi suçlu veya yetersiz hissettirmek",
      noReplyAction: "Bir daha yazmayacağım",
    },
  },
  {
    id: "borc-geri-isteme",
    title: "Arkadaştan Borcu İsteme",
    description: "Zamanında verdiğiniz ve geciken borcu, arkadaşlığınızı zedelemeden geri isteyin.",
    category: "para_pazarlik",
    difficulty: "Orta",
    context: {
      incomingMessage: "Sana geçen ay verdiğim borcun durumunu sormak durumundayım.",
      otherPerson: "Arkadaş",
      otherPersonPersonality: "Alıngan ve Hassas",
      difficultyReason: "Arkadaştan alacağımı istemek",
      goal: "Sınır koymak",
      tone: "Uzlaşmacı",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      fear: "kırgınlık yaşamak veya paragöz görünmek",
      financialIssue: "Borç / Alacak",
      currentAmount: "10.000 TL",
      minAcceptableLevel: "Bu hafta sonuna kadar en azından yarısının ödenmesi",
      otherPersonAttitude: "Ödemeyi geciktiriyor",
      leverageOrAlternative: "Söz verdiğine dair eski Whatsapp mesajlaşmaları",
      noAgreementAction: "Süre isterim",
    },
  },
  {
    id: "istifa-bildirimi",
    title: "Yöneticiye İstifa Kararı",
    description: "Yeni bir iş teklifi aldınız. Şirketten profesyonelce ve dostane ayrılma provası yapın.",
    category: "is_kariyer",
    difficulty: "Orta",
    context: {
      incomingMessage: "Kariyerimde yeni bir adım atmak amacıyla istifa kararımı paylaşmak istiyorum.",
      otherPerson: "Yönetici / Müdür",
      otherPersonPersonality: "Anlayışlı ve Mantıklı",
      difficultyReason: "İstifa etmek / ayrılmak",
      goal: "İstifa etmek",
      tone: "Profesyonel ve kibar",
      replyLength: "Detaylı mesaj",
      preserveRelationship: "Sadece saygılı kapatmak istiyorum",
      fear: "yöneticinin sinirlenmesi veya referans sorunu",
      otherPersonAttitude: "Anlayışlı",
      previouslyDiscussed: "Hayır, ilk kez açılacak",
      redLine: "İhbar süresinden daha fazla kalmayı kabul edemem",
    },
  },
  {
    id: "akraba-borc-reddi",
    title: "Akraba Borç Talebi Reddi",
    description: "Maddi durumunu bahane ederek sürekli borç isteyen yakın bir akrabanızı kırmadan geri çevirin.",
    category: "aile_arkadas",
    difficulty: "Orta",
    context: {
      incomingMessage: "Yeğenim/kuzenim, şu ara sıkıştım da bana bir 20 bin TL borç gönderebilir misin haftaya öderim.",
      otherPerson: "Akraba / Kuzen",
      otherPersonPersonality: "Geleneksel / Israrcı",
      difficultyReason: "Yakın birine hayır demek",
      goal: "Hayır demek",
      tone: "Kırmadan sınır koyan",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      fear: "akraba içinde bencil görünmek veya küslük yaşamak",
      closenessLevel: "Yakın ama hassas",
      otherPersonAttitude: "Suçluluk hissettirebilir",
      pastConversations: "Ben susuyorum",
    },
  },
  {
    id: "gec-cevap-flort",
    title: "Geç Cevap Veren Flört",
    description: "Mesajlarınıza saatler sonra dönen flörtünüze bu durumdan rahatsız olduğunuzu kibarca hissettirin.",
    category: "flort_iliski",
    difficulty: "Orta",
    context: {
      incomingMessage: "Kusura bakma canım ya yoğunluktan anca bakabildim telefona. Naber?",
      otherPerson: "Flört",
      otherPersonPersonality: "İlgisiz / Kararsız",
      difficultyReason: "Soğuk davranılmasını sorgulamak",
      goal: "Niyetini anlamak",
      tone: "Net ve mesafeli",
      replyLength: "Tek cümle",
      preserveRelationship: "Emin değilim",
      fear: "fazla istekli görünmek veya trip atıyor gibi olmak",
      relationshipDuration: "Birkaç hafta",
      otherPersonAttitude: "Geç cevap veriyor",
      avoidAction: "Öfkeyle sitem etmek",
      noReplyAction: "Bekleyeceğim",
    },
  },
  {
    id: "eski-sevgili-donus",
    title: "Eski Sevgilinin Dönüşü",
    description: "Aylar sonra birdenbire 'nasılsın?' diye yazan eski sevgilinize net sınırlarınızı çizin.",
    category: "flort_iliski",
    difficulty: "Zor",
    context: {
      incomingMessage: "Selam, geçen gün seni düşündüm de... Nasılsın, her şey yolunda mı?",
      otherPerson: "Eski sevgili",
      otherPersonPersonality: "Soğuk ve Mesafeli",
      difficultyReason: "Eski sevgiliye yanıt vermek",
      goal: "Mesafe koymak",
      tone: "Net ve mesafeli",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Hayır",
      fear: "tekrar duygusal karmaşaya girmek veya zayıf görünmek",
      relationshipDuration: "Çok uzun süre",
      otherPersonAttitude: "Kararsız",
      avoidAction: "Hemen yumuşayıp buluşmayı kabul etmek",
      noReplyAction: "Bir daha yazmayacağım",
    },
  },
  {
    id: "is-arkadasi-sinir",
    title: "İş Arkadaşına Sınır Koyma",
    description: "Kendi yapması gereken işi veya sorumlulukları sürekli sizin üzerinize yıkmaya çalışan meslektaşınızı durdurun.",
    category: "is_kariyer",
    difficulty: "Orta",
    context: {
      incomingMessage: "Ya ben bugün biraz yoğunum da, şu raporun kalan kısmını sen halledebilir misin rica etsem?",
      otherPerson: "İş arkadaşı",
      otherPersonPersonality: "Pasif-Agresif / İğneleyici",
      difficultyReason: "İş yükümü azaltmak",
      goal: "Sınır koymak",
      tone: "Net ve kararlı",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      fear: "ekip içinde uyumsuz görünmek veya kavga çıkması",
      otherPersonAttitude: "Savunmacı",
      previouslyDiscussed: "Evet, kötü geçti",
      redLine: "Kendi teslim tarihlerimi aksatacak ek iş yükü alamam",
    },
  },
  {
    id: "musteri-indirim-reddi",
    title: "Müşteri İndirim Reddi",
    description: "Zaten uygun olan fiyat teklifinize ekstra indirim talep eden ısrarcı müşteriyi ikna edin.",
    category: "para_pazarlik",
    difficulty: "Orta",
    context: {
      incomingMessage: "Teklifiniz çok güzel ama bütçemizi aşıyor. %20 daha indirim yaparsanız hemen başlayalım.",
      otherPerson: "Müşteri",
      otherPersonPersonality: "Israrcı ve Zorlayıcı",
      difficultyReason: "Müşterinin indirim talebini reddetmek",
      goal: "İndirim yapmadan satmak",
      tone: "Sert ama saygılı",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      fear: "müşteriyi rakibe kaptırmak veya kaba görünmek",
      financialIssue: "Freelance / Hizmet bedeli",
      currentAmount: "50.000 TL",
      minAcceptableLevel: "Ekstra kapsam azaltımı olmadan indirim yapamam",
      otherPersonAttitude: "İndirim istiyor",
      leverageOrAlternative: "Benzer kalitedeki projelerin piyasa değeri",
      noAgreementAction: "Masadan kalkarım",
    },
  },
  {
    id: "konuyu-kapatma",
    title: "Rahatsız Edici Konuyu Kapatma",
    description: "Arkadaş ortamında sürekli açılan ve sizi rahatsız eden özel bir konuyu kırmadan kapatın.",
    category: "zor_mesajlar",
    difficulty: "Kolay",
    context: {
      incomingMessage: "Eee senin şu özel hayat/iş konusu ne oldu ya? Hala bir gelişme yok mu, anlatsana?",
      otherPerson: "Arkadaş",
      otherPersonPersonality: "Alıngan ve Hassas",
      difficultyReason: "Konuyu kapatmak",
      goal: "Tartışmayı kapatmak",
      tone: "Kırmadan ama kararlı",
      replyLength: "Tek cümle",
      preserveRelationship: "Evet",
      fear: "arkadaşımın alınması veya gizemli görünmek",
      closenessLevel: "Çok yakın",
      otherPersonAttitude: "Alınabilir",
      pastConversations: "Genelde tartışmaya dönüyor",
    },
  },
];
