import type { MessageContext } from "./types";

export type SimulationTemplate = {
  id: string;
  title: string;
  description: string;
  category: "is_kariyer" | "flort_iliski" | "aile_arkadas" | "para_pazarlik" | "zor_mesajlar" | "egitim_okul" | "gunluk_yasam";
  difficulty: "Kolay" | "Orta" | "Zor";
  context: MessageContext;
};

export const templates: SimulationTemplate[] = [
  {
    id: "patron-zam",
    title: "Patrondan Zam İsteme",
    description: "Sorumluluklarınız arttı ama maaşınız aynı kaldı. Köprüleri yakmadan zam isteyin.",
    category: "is_kariyer",
    difficulty: "Orta",
    context: {
      incomingMessage: "Son dönemdeki performansım ve artan sorumluluklarım hakkında görüşmek istiyorum.",
      otherPerson: "Patron",
      otherPersonPersonality: "Anlayışlı ve Mantıklı",
      difficultyReason: "Zam istemek / hakkımı savunmak",
      goal: "Zam almak",
      tone: "Yumuşak ama ciddi",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      fear: "gözden düşmek veya reddedilmek",
      otherPersonAttitude: "Savunmacı",
      previouslyDiscussed: "Hayır, ilk kez açılacak",
      redLine: "Sektör ortalamasının altında bir artışı kabul etmem",
    },
  },
  {
    id: "mesai-reddi",
    title: "Hafta Sonu Mesai Reddi",
    description: "Yöneticinizin son dakika ilettiği hafta sonu çalışma talebini profesyonelce geri çevirin.",
    category: "is_kariyer",
    difficulty: "Kolay",
    context: {
      incomingMessage: "Hafta sonu acil bir teslimat var, cumartesi günü ofise gelebilir misin?",
      otherPerson: "Yönetici / Müdür",
      otherPersonPersonality: "Yoğun ve Dikkatsiz",
      difficultyReason: "Fazla mesaiyi kibarca reddetmek",
      goal: "Profesyonelce reddetmek",
      tone: "Profesyonel ve kibar",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      fear: "isteksiz görünmek veya tepki çekmek",
      otherPersonAttitude: "Kaçamak",
      previouslyDiscussed: "Hayır, ilk kez açılacak",
      redLine: "Hafta sonu planımı iptal edemem",
    },
  },
  {
    id: "kira-artisi",
    title: "Kira Artışına İtiraz",
    description: "Ev sahibinin yasal sınırın çok üzerindeki fahiş kira artış talebine karşı sınırlarınızı çizin.",
    category: "para_pazarlik",
    difficulty: "Zor",
    context: {
      incomingMessage: "Biliyorsun piyasa uçtu. Kirayı iki katına çıkarmamız gerekiyor, ne dersin?",
      otherPerson: "Ev sahibi",
      otherPersonPersonality: "Para Göz ve Katı",
      difficultyReason: "Kira artışına itiraz etmek / anlaşmak",
      goal: "Sınır koymak",
      tone: "Sert ama saygılı",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Sadece saygılı kapatmak istiyorum",
      fear: "evden çıkarılmak veya kavga etmek",
      financialIssue: "Kira artışı",
      currentAmount: "15.000 TL",
      minAcceptableLevel: "Yasal sınır olan %65 artışın üstüne çıkamam",
      otherPersonAttitude: "Artışı kabul etmiyor",
      leverageOrAlternative: "Banka ödeme dekontları ve yasal kira artış oranı",
      noAgreementAction: "Alternatif teklif sunarım",
    },
  },
  {
    id: "flort-netlik",
    title: "Flörte Netlik Sorusu",
    description: "Bir süredir belirsiz veya soğuk davranan flörtünüze hislerinizi ve durumu açın.",
    category: "flort_iliski",
    difficulty: "Orta",
    context: {
      incomingMessage: "İlişkimizin son dönemdeki soğukluğu ve iletişim belirsizliği hakkında konuşmak istiyorum.",
      otherPerson: "Flört",
      otherPersonPersonality: "Soğuk ve Mesafeli",
      difficultyReason: "İlişkiyi adlandırmak / netlik istemek",
      goal: "Niyetini anlamak",
      tone: "Samimi ve açık",
      replyLength: "Detaylı mesaj",
      preserveRelationship: "Evet",
      fear: "tamamen kopmak veya gurursuz görünmek",
      relationshipDuration: "Birkaç ay",
      otherPersonAttitude: "İlgili ama belirsiz",
      avoidAction: "Kendimi suçlu veya yetersiz hissettirmek",
      noReplyAction: "Bir daha yazmayacağım",
    },
  },
  {
    id: "borc-geri-isteme",
    title: "Arkadaştan Borcu İsteme",
    description: "Zamanında verdiğiniz ve geciken borcu, arkadaşlığınızı zedelemeden geri isteyin.",
    category: "para_pazarlik",
    difficulty: "Orta",
    context: {
      incomingMessage: "Sana geçen ay verdiğim borcun durumunu sormak durumundayım.",
      otherPerson: "Arkadaş",
      otherPersonPersonality: "Alıngan ve Hassas",
      difficultyReason: "Arkadaştan alacağımı istemek",
      goal: "Sınır koymak",
      tone: "Uzlaşmacı",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      fear: "kırgınlık yaşamak veya paragöz görünmek",
      financialIssue: "Borç / Alacak",
      currentAmount: "10.000 TL",
      minAcceptableLevel: "Bu hafta sonuna kadar en azından yarısının ödenmesi",
      otherPersonAttitude: "Ödemeyi geciktiriyor",
      leverageOrAlternative: "Söz verdiğine dair eski Whatsapp mesajlaşmaları",
      noAgreementAction: "Süre isterim",
    },
  },
  {
    id: "istifa-bildirimi",
    title: "Yöneticiye İstifa Kararı",
    description: "Yeni bir iş teklifi aldınız. Şirketten profesyonelce ve dostane ayrılma provası yapın.",
    category: "is_kariyer",
    difficulty: "Orta",
    context: {
      incomingMessage: "Kariyerimde yeni bir adım atmak amacıyla istifa kararımı paylaşmak istiyorum.",
      otherPerson: "Yönetici / Müdür",
      otherPersonPersonality: "Anlayışlı ve Mantıklı",
      difficultyReason: "İstifa etmek / ayrılmak",
      goal: "İstifa etmek",
      tone: "Profesyonel ve kibar",
      replyLength: "Detaylı mesaj",
      preserveRelationship: "Sadece saygılı kapatmak istiyorum",
      fear: "yöneticinin sinirlenmesi veya referans sorunu",
      otherPersonAttitude: "Anlayışlı",
      previouslyDiscussed: "Hayır, ilk kez açılacak",
      redLine: "İhbar süresinden daha fazla kalmayı kabul edemem",
    },
  },
  {
    id: "akraba-borc-reddi",
    title: "Akraba Borç Talebi Reddi",
    description: "Maddi durumunu bahane ederek sürekli borç isteyen yakın bir akrabanızı kırmadan geri çevirin.",
    category: "aile_arkadas",
    difficulty: "Orta",
    context: {
      incomingMessage: "Yeğenim/kuzenim, şu ara sıkıştım da bana bir 20 bin TL borç gönderebilir misin haftaya öderim.",
      otherPerson: "Akraba / Kuzen",
      otherPersonPersonality: "Geleneksel / Israrcı",
      difficultyReason: "Yakın birine hayır demek",
      goal: "Hayır demek",
      tone: "Kırmadan sınır koyan",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      fear: "akraba içinde bencil görünmek veya küslük yaşamak",
      closenessLevel: "Yakın ama hassas",
      otherPersonAttitude: "Suçluluk hissettirebilir",
      pastConversations: "Ben susuyorum",
    },
  },
  {
    id: "gec-cevap-flort",
    title: "Geç Cevap Veren Flört",
    description: "Mesajlarınıza saatler sonra dönen flörtünüze bu durumdan rahatsız olduğunuzu kibarca hissettirin.",
    category: "flort_iliski",
    difficulty: "Orta",
    context: {
      incomingMessage: "Kusura bakma canım ya yoğunluktan anca bakabildim telefona. Naber?",
      otherPerson: "Flört",
      otherPersonPersonality: "İlgisiz / Kararsız",
      difficultyReason: "Soğuk davranılmasını sorgulamak",
      goal: "Niyetini anlamak",
      tone: "Net ve mesafeli",
      replyLength: "Tek cümle",
      preserveRelationship: "Emin değilim",
      fear: "fazla istekli görünmek veya trip atıyor gibi olmak",
      relationshipDuration: "Birkaç hafta",
      otherPersonAttitude: "Geç cevap veriyor",
      avoidAction: "Öfkeyle sitem etmek",
      noReplyAction: "Bekleyeceğim",
    },
  },
  {
    id: "eski-sevgili-donus",
    title: "Eski Sevgilinin Dönüşü",
    description: "Aylar sonra birdenbire 'nasılsın?' diye yazan eski sevgilinize net sınırlarınızı çizin.",
    category: "flort_iliski",
    difficulty: "Zor",
    context: {
      incomingMessage: "Selam, geçen gün seni düşündüm de... Nasılsın, her şey yolunda mı?",
      otherPerson: "Eski sevgili",
      otherPersonPersonality: "Soğuk ve Mesafeli",
      difficultyReason: "Eski sevgiliye yanıt vermek",
      goal: "Mesafe koymak",
      tone: "Net ve mesafeli",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Hayır",
      fear: "tekrar duygusal karmaşaya girmek veya zayıf görünmek",
      relationshipDuration: "Çok uzun süre",
      otherPersonAttitude: "Kararsız",
      avoidAction: "Hemen yumuşayıp buluşmayı kabul etmek",
      noReplyAction: "Bir daha yazmayacağım",
    },
  },
  {
    id: "is-arkadasi-sinir",
    title: "İş Arkadaşına Sınır Koyma",
    description: "Kendi yapması gereken işi veya sorumlulukları sürekli sizin üzerinize yıkmaya çalışan meslektaşınızı durdurun.",
    category: "is_kariyer",
    difficulty: "Orta",
    context: {
      incomingMessage: "Ya ben bugün biraz yoğunum da, şu raporun kalan kısmını sen halledebilir misin rica etsem?",
      otherPerson: "İş arkadaşı",
      otherPersonPersonality: "Pasif-Agresif / İğneleyici",
      difficultyReason: "İş yükümü azaltmak",
      goal: "Sınır koymak",
      tone: "Net ve kararlı",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      fear: "ekip içinde uyumsuz görünmek veya kavga çıkması",
      otherPersonAttitude: "Savunmacı",
      previouslyDiscussed: "Evet, kötü geçti",
      redLine: "Kendi teslim tarihlerimi aksatacak ek iş yükü alamam",
    },
  },
  {
    id: "musteri-indirim-reddi",
    title: "Müşteri İndirim Reddi",
    description: "Zaten uygun olan fiyat teklifinize ekstra indirim talep eden ısrarcı müşteriyi ikna edin.",
    category: "para_pazarlik",
    difficulty: "Orta",
    context: {
      incomingMessage: "Teklifiniz çok güzel ama bütçemizi aşıyor. %20 daha indirim yaparsanız hemen başlayalım.",
      otherPerson: "Müşteri",
      otherPersonPersonality: "Israrcı ve Zorlayıcı",
      difficultyReason: "Müşterinin indirim talebini reddetmek",
      goal: "İndirim yapmadan satmak",
      tone: "Sert ama saygılı",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      fear: "müşteriyi rakibe kaptırmak veya kaba görünmek",
      financialIssue: "Freelance / Hizmet bedeli",
      currentAmount: "50.000 TL",
      minAcceptableLevel: "Ekstra kapsam azaltımı olmadan indirim yapamam",
      otherPersonAttitude: "İndirim istiyor",
      leverageOrAlternative: "Benzer kalitedeki projelerin piyasa değeri",
      noAgreementAction: "Masadan kalkarım",
    },
  },
  {
    id: "konuyu-kapatma",
    title: "Rahatsız Edici Konuyu Kapatma",
    description: "Arkadaş ortamında sürekli açılan ve sizi rahatsız eden özel bir konuyu kırmadan kapatın.",
    category: "zor_mesajlar",
    difficulty: "Kolay",
    context: {
      incomingMessage: "Eee senin şu özel hayat/iş konusu ne oldu ya? Hala bir gelişme yok mu, anlatsana?",
      otherPerson: "Arkadaş",
      otherPersonPersonality: "Alıngan ve Hassas",
      difficultyReason: "Konuyu kapatmak",
      goal: "Tartışmayı kapatmak",
      tone: "Kırmadan ama kararlı",
      replyLength: "Tek cümle",
      preserveRelationship: "Evet",
      fear: "arkadaşımın alınması veya gizemli görünmek",
      closenessLevel: "Çok yakın",
      otherPersonAttitude: "Alınabilir",
      pastConversations: "Genelde tartışmaya dönüyor",
    },
  },

  // === NEW 20 TEMPLATES START HERE ===

  // --- İŞ / KARİYER ---
  {
    id: "terfi-talebi",
    title: "Yöneticiden Terfi İsteme",
    description: "Ekip liderliğine aday olmak istiyorsunuz. Yöneticinize hedefinizi ve liyakatinizi anlatın.",
    category: "is_kariyer",
    difficulty: "Zor",
    context: {
      incomingMessage: "Son altı aydır ekibin tüm teknik koordinasyonunu ve yeni üyelerin oryantasyonunu ben yürütüyorum.",
      otherPerson: "Yönetici / Müdür",
      otherPersonPersonality: "Anlayışlı ve Mantıklı",
      difficultyReason: "Zam istemek / hakkımı savunmak",
      goal: "Zam almak",
      tone: "Yumuşak ama ciddi",
      replyLength: "Detaylı mesaj",
      preserveRelationship: "Evet",
      fear: "hırslı görünmek veya reddedilip hayal kırıklığı yaşamak",
      otherPersonAttitude: "Pazarlıkçı",
      previouslyDiscussed: "Hayır, ilk kez açılacak",
      redLine: "Görev tanımım değişmeden yeni sorumlulukları kalıcı olarak üstlenmem",
    },
  },
  {
    id: "is-gorusmesi-pazarlik",
    title: "Mülakatta Maaş Pazarlığı",
    description: "Teklif edilen maaş beklentinizin altında kaldı. Profesyonelce kendi değerinizi müzakere edin.",
    category: "is_kariyer",
    difficulty: "Zor",
    context: {
      incomingMessage: "Sizi ekibimizde görmek isteriz. Aylık net bütçemiz 40.000 TL olarak belirlendi. Nasıl buldunuz?",
      otherPerson: "IK (İnsan Kaynakları)",
      otherPersonPersonality: "Otoriter ve Sert",
      difficultyReason: "Zam istemek / hakkımı savunmak",
      goal: "Zam almak",
      tone: "Net ve kararlı",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      fear: "teklifin tamamen geri çekilmesi",
      otherPersonAttitude: "Pazarlıkçı",
      previouslyDiscussed: "Hayır, ilk kez açılacak",
      redLine: "45.000 TL ve yan hakların altına imza atmam",
    },
  },
  {
    id: "ekip-arkadasi-geri-bildirim",
    title: "İşini Aksatan Arkadaşı Uyarma",
    description: "Projedeki gecikmeleri sürekli sizin üzerinize atan ekip arkadaşınızla net konuşun.",
    category: "is_kariyer",
    difficulty: "Orta",
    context: {
      incomingMessage: "Ya kusura bakma benim kısım biraz gecikti ama sunumda ikimizin adı var nasıl olsa, sen halledersin değil mi?",
      otherPerson: "İş arkadaşı",
      otherPersonPersonality: "Pasif-Agresif / İğneleyici",
      difficultyReason: "Ekip arkadaşıma geribildirim vermek",
      goal: "Geri bildirim vermek",
      tone: "Net ve kararlı",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      fear: "ofis içinde huzursuzluk yaratmak veya bencil damgası yemek",
      otherPersonAttitude: "Savunmacı",
      previouslyDiscussed: "Evet, olumlu geçti",
      redLine: "Başkalarının gecikmelerini üstlenerek gece mesaisi yapmam",
    },
  },
  {
    id: "haksiz-elestiri-cevap",
    title: "Haksız Eleştiriye Yanıt",
    description: "Yöneticinizin tüm ekibin önünde yaptığı haksız suçlamaya profesyonelce sınır çizin.",
    category: "is_kariyer",
    difficulty: "Orta",
    context: {
      incomingMessage: "Bu projenin bu kadar gecikmesinin tek sebebi senin detaylarda aşırı boğulmandır.",
      otherPerson: "Yönetici / Müdür",
      otherPersonPersonality: "Yoğun ve Dikkatsiz",
      difficultyReason: "Haksız eleştiriye profesyonel yanıt vermek",
      goal: "Sınır koymak",
      tone: "Profesyonel ve kibar",
      replyLength: "Detaylı mesaj",
      preserveRelationship: "Evet",
      fear: "patronla tartışmak veya saygısız görünmek",
      otherPersonAttitude: "Sert",
      previouslyDiscussed: "Hayır, ilk kez açılacak",
      redLine: "Gecikmeye neden olan onay süreçlerinin atlanmasını kabul etmem",
    },
  },
  {
    id: "is-yuku-azaltma",
    title: "Aşırı İş Yükünün Azaltılması",
    description: "Tükenmişlik noktasına geldiniz. Yöneticinize iş yükünüzün optimize edilmesi talebini sunun.",
    category: "is_kariyer",
    difficulty: "Orta",
    context: {
      incomingMessage: "Son üç aydır üç kişilik projeyi tek başıma yürütmeye çalışıyorum, verimliliğim düşüyor.",
      otherPerson: "Yönetici / Müdür",
      otherPersonPersonality: "Manipülatif ve Egoist",
      difficultyReason: "İş yükümü azaltmak",
      goal: "Sınır koymak",
      tone: "Yumuşak ama ciddi",
      replyLength: "Detaylı mesaj",
      preserveRelationship: "Evet",
      fear: "beceriksiz veya zayıf görünmek",
      otherPersonAttitude: "Kaçamak",
      previouslyDiscussed: "Yes, kötü geçti",
      redLine: "Yeni bir uzman alınana kadar fazla mesai yapmayı kabul etmem",
    },
  },

  // --- FLÖRT / İLİŞKİ ---
  {
    id: "ilk-mesaj-flort",
    title: "Beğenilen Kişiye İlk Mesaj",
    description: "Sosyal medyada veya bir ortamda karşılaştığınız kişiye doğal ve cool bir açılış yapın.",
    category: "flort_iliski",
    difficulty: "Kolay",
    context: {
      incomingMessage: "Profilindeki müzik paylaşımını gördüm, bu grubu ben de çok seviyorum.",
      otherPerson: "Yeni tanışılan biri",
      relationshipDuration: "Birkaç gün",
      otherPersonPersonality: "Anlayışlı ve Açık Sözlü",
      otherPersonAttitude: "İlgili ama belirsiz",
      difficultyReason: "İlişkiyi adlandırmak / netlik istemek",
      goal: "Niyetini anlamak",
      tone: "Hafif esprili",
      replyLength: "Tek cümle",
      preserveRelationship: "Evet",
      avoidAction: "Çok abartılı iltifatlar veya muhtaç bir ton kullanmak",
      noReplyAction: "Bir daha yazmayacağım",
      fear: "görüldü yiyip rezil olmak veya cevapsız kalmak",
    },
  },
  {
    id: "iliski-adi-koyma",
    title: "Biz Neyiz? Konuşması",
    description: "Aylardır süren flört evresinden sonra ilişkinin adını koymak istediğinizi belirtin.",
    category: "flort_iliski",
    difficulty: "Zor",
    context: {
      incomingMessage: "İlişkimizin şu anki yönü ve geleceği hakkında netleşmek istiyorum.",
      otherPerson: "Flört",
      relationshipDuration: "Birkaç ay",
      otherPersonPersonality: "Anlayışlı ve Açık Sözlü",
      otherPersonAttitude: "Kararsız",
      difficultyReason: "İlişkiyi adlandırmak / netlik istemek",
      goal: "Niyetini anlamak",
      tone: "Samimi ve açık",
      replyLength: "Detaylı mesaj",
      preserveRelationship: "Evet",
      avoidAction: "Karşı tarafa ultimatom vermek veya baskı uygulamak",
      noReplyAction: "Mesafe koymak istiyorum",
      fear: "Karşı tarafın kaçması veya hazır değilim demesi",
    },
  },
  {
    id: "kiskanc-flort-sinir",
    title: "Kıskanç Sevgiliye Sınır Çizme",
    description: "Sosyal hayatınıza ve arkadaşlıklarınıza aşırı müdahale eden sevgilinize sınırlarınızı belirtin.",
    category: "flort_iliski",
    difficulty: "Orta",
    context: {
      incomingMessage: "O arkadaşlarınla bu kadar sık görüşmeni ve dışarı çıkmanı istemiyorum, beni rahatsız ediyor.",
      otherPerson: "Sevgili",
      relationshipDuration: "Birkaç ay",
      otherPersonPersonality: "Kıskanç ve Koruyucu",
      otherPersonAttitude: "Suçlayıcı",
      difficultyReason: "Kıskançlık / güven konusunu açmak",
      goal: "Kırmadan sınır koymak",
      tone: "Sakin",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      avoidAction: "Kavga etmek veya hemen taviz verip arkadaşlarımı silmek",
      noReplyAction: "Bekleyeceğim",
      fear: "Kavganın büyümesi veya güvensizlikle suçlanmak",
    },
  },
  {
    id: "ayrilik-konusmasi",
    title: "İlişkiyi Kibarca Bitirme",
    description: "Karşı tarafa olan hislerinizin bittiğini, onu kırmadan ama net bir şekilde iletin.",
    category: "flort_iliski",
    difficulty: "Orta",
    context: {
      incomingMessage: "Son zamanlarda aramızdaki kopukluğu hissediyorum, bir şeyler ters gidiyor sanki.",
      otherPerson: "Sevgili",
      relationshipDuration: "Birkaç ay",
      otherPersonPersonality: "Duygusal ve Hassas",
      otherPersonAttitude: "Duygusal ve Hassas",
      difficultyReason: "Kibarca mesafe koymak / bitirmek",
      goal: "İlişkiyi bitirmek",
      tone: "Net ve mesafeli",
      replyLength: "Detaylı mesaj",
      preserveRelationship: "Sadece saygılı kapatmak istiyorum",
      avoidAction: "Umut vermek veya bahaneler arkasına sığınmak",
      noReplyAction: "Bir daha yazmayacağım",
      fear: "Karşı tarafın ağlaması veya suçluluk psikolojisi yaratması",
    },
  },
  {
    id: "barisma-provasi",
    title: "Kırılan Sevgiliyle Barışma",
    description: "Yaptığınız bir hata yüzünden kırılan partnerinize hatanızı kabul edip samimi bir özür dileyin.",
    category: "flort_iliski",
    difficulty: "Kolay",
    context: {
      incomingMessage: "O günkü tavrın beni gerçekten çok kırdı, konuşmak istemiyorum şu an.",
      otherPerson: "Sevgili",
      relationshipDuration: "Çok uzun süre",
      otherPersonPersonality: "Duygusal ve Hassas",
      otherPersonAttitude: "Savunmacı",
      difficultyReason: "Kırgınlığımı dile getirmek",
      goal: "Özür dilemek ve barışmak",
      tone: "Samimi ve açık",
      replyLength: "Detaylı mesaj",
      preserveRelationship: "Evet",
      avoidAction: "Kendi hatamı küçümsemek veya karşı tarafı suçlamak",
      noReplyAction: "Bekleyeceğim",
      fear: "Reddedilmek veya özrümün samimi bulunmaması",
    },
  },

  // --- AİLE / ARKADAŞ ---
  {
    id: "arkadas-kirginlik",
    title: "Arkadaşa Kırgınlık İletme",
    description: "Sürekli planları son dakika iptal eden arkadaşınıza hissettiğiniz kırgınlığı belirtin.",
    category: "aile_arkadas",
    difficulty: "Kolay",
    context: {
      incomingMessage: "Ya kanka çok acil bir işim çıktı, bugün buluşmayı erteleyelim mi ya?",
      otherPerson: "Yakın arkadaş",
      closenessLevel: "Çok yakın",
      otherPersonPersonality: "Pasif-Agresif",
      otherPersonAttitude: "Konuyu değiştirebilir",
      pastConversations: "Ben susuyorum",
      difficultyReason: "Yakın birinin kırıcı davranışını söylemek",
      goal: "Kırmadan sınır koymak",
      tone: "Sakin ama net",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      fear: "Trip atmakla suçlanmak veya arkadaşlığı kaybetmek",
    },
  },
  {
    id: "aile-karar-aciklama",
    title: "Aileye Kariyer Kararını Açıklama",
    description: "İstemediğiniz bir bölümü/işi bırakıp kendi hedefinize yöneleceğinizi ailenize kararlılıkla anlatın.",
    category: "aile_arkadas",
    difficulty: "Zor",
    context: {
      incomingMessage: "Kariyerimde kendi yeteneklerime uygun, farklı bir alanda ilerlemeye karar verdim.",
      otherPerson: "Baba",
      closenessLevel: "Aile olduğu için kopmak istemiyorum",
      otherPersonPersonality: "Otoriter ve Baskıcı",
      otherPersonAttitude: "Kızabilir",
      pastConversations: "Karşı taraf savunmaya geçiyor",
      difficultyReason: "Aileye kendi kararlarımı açıklamak",
      goal: "Kararımı kabul ettirmek",
      tone: "Sakin ama net",
      replyLength: "Detaylı mesaj",
      preserveRelationship: "Evet",
      fear: "Maddi desteği kesmeleri veya hayal kırıklığı yaratmak",
    },
  },
  {
    id: "arkadas-borc-hatirlatma",
    title: "Arkadaştan Borcu Hatırlatma",
    description: "Üzerinden aylar geçen borcu arkadaşınıza dostluğunuzu bozmadan hatırlatın.",
    category: "aile_arkadas",
    difficulty: "Orta",
    context: {
      incomingMessage: "Geçen aylarda yaptığımız borç alışverişinin durumunu konuşabilir miyiz?",
      otherPerson: "Yakın arkadaş",
      closenessLevel: "Yakın ama hassas",
      otherPersonPersonality: "Alıngan ve Hassas",
      otherPersonAttitude: "Alınabilir",
      pastConversations: "Genelde iyi",
      difficultyReason: "Arkadaşa borcunu hatırlatmak",
      goal: "Borcumu tahsil etmek",
      tone: "Kırmadan sınır koyan",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      fear: "Paragöz gibi görünmek veya arkadaşın gücenmesi",
    },
  },
  {
    id: "davet-iptali-kibar",
    title: "Son Dakika Davet İptali",
    description: "Katılacağınızı söylediğiniz bir arkadaş davetini, geçerli bir sebeple kırmadan son dakika iptal edin.",
    category: "aile_arkadas",
    difficulty: "Kolay",
    context: {
      incomingMessage: "Akşama her şey hazır, sabırsızlıkla bekliyorum geleceksin değil mi?",
      otherPerson: "Yakın arkadaş",
      closenessLevel: "Çok yakın",
      otherPersonPersonality: "Destekleyici ve Sevgi Dolu",
      otherPersonAttitude: "Anlayışlı olabilir",
      pastConversations: "Genelde iyi",
      difficultyReason: "Planı kırmadan iptal etmek",
      goal: "Hayır demek",
      tone: "Çok yumuşak",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      fear: "Güvenilmez biri olarak algılanmak",
    },
  },
  {
    id: "aile-baski-evlilik",
    title: "Ailenin Evlilik Baskısını Durdurma",
    description: "Sürekli ne zaman evleneceğinizi soran ısrarcı ailenize hayatınızın kontrolünün sizde olduğunu iletin.",
    category: "aile_arkadas",
    difficulty: "Orta",
    context: {
      incomingMessage: "Yaşın geçiyor evladım, artık birini bulup yuva kurmanın zamanı gelmedi mi?",
      otherPerson: "Anne",
      closenessLevel: "Aile olduğu için kopmak istemiyorum",
      otherPersonPersonality: "Geleneksel / Israrcı",
      otherPersonAttitude: "Suçluluk hissettirebilir",
      pastConversations: "Ben susuyorum",
      difficultyReason: "Yakın birine hayır demek",
      goal: "Kırmadan sınır koymak",
      tone: "Kırmadan sınır koyan",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      fear: "Hayırsız evlat ilan edilmek veya vicdan azabı çekmek",
    },
  },

  // --- PARA / PAZARLIK ---
  {
    id: "kira-artisi-evsahibi",
    title: "Kiracıyla Kira Artışı",
    description: "Enflasyon karşısında eriyen kiranızı kiracınızla orta yolu bularak artırma konuşması yapın.",
    category: "para_pazarlik",
    difficulty: "Orta",
    context: {
      incomingMessage: "Mevcut ekonomik şartlar nedeniyle kira bedelini güncellememiz gerekiyor.",
      otherPerson: "Kiracı",
      otherPersonPersonality: "Uzlaşmacı ve Esnek",
      financialIssue: "Kira artışı",
      currentAmount: "10.000 TL",
      minAcceptableLevel: "En az 16.000 TL düzeyine çıkarılması",
      otherPersonAttitude: "Pahalı buluyor",
      leverageOrAlternative: "Çevredeki emsal evlerin kira bedelleri",
      difficultyReason: "Kira artışına itiraz etmek / anlaşmak",
      goal: "Hedef tutarda anlaşmak",
      tone: "Uzlaşmacı",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      noAgreementAction: "Alternatif teklif sunarım",
      fear: "Kiracının ödeme yapmayı tamamen durdurması veya mahkemelik olmak",
    },
  },
  {
    id: "freelance-fiyat-savunma",
    title: "Freelance Fiyatını Savunma",
    description: "Sunduğunuz teklifi aşırı pahalı bulan kurumsal müşteriye emeğinizin değerini savunun.",
    category: "para_pazarlik",
    difficulty: "Zor",
    context: {
      incomingMessage: "Tasarım teklifiniz piyasanın oldukça üzerinde. Bize daha uygun bir fiyat veremez misiniz?",
      otherPerson: "Müşteri",
      otherPersonPersonality: "Israrcı ve Zorlayıcı",
      financialIssue: "Freelance / Hizmet bedeli",
      currentAmount: "30.000 TL",
      minAcceptableLevel: "Fiyatta indirim yapamam ancak revizyon haklarını sınırlayabilirim",
      otherPersonAttitude: "Pahalı buluyor",
      leverageOrAlternative: "Geçmiş referanslarım ve teslim edeceğim yüksek kaliteli kaynak kodlar",
      difficultyReason: "Serbest çalışan olarak fiyatımı savunmak",
      goal: "İndirim yapmadan satmak",
      tone: "Sert ama saygılı",
      replyLength: "Detaylı mesaj",
      preserveRelationship: "Evet",
      noAgreementAction: "Masadan kalkarım",
      fear: "Portföye eklenebilecek iyi bir müşteriyi kaybetmek",
    },
  },

  // --- ZOR MESAJLAR ---
  {
    id: "goruldu-sonrasi-yazma",
    title: "Görüldü Atan Flörte Cool Mesaj",
    description: "Yazdığınız mesaja görüldü atan kişiye muhtaç duruma düşmeden cool bir şekilde konuyu kapatma mesajı yazın.",
    category: "zor_mesajlar",
    difficulty: "Kolay",
    context: {
      incomingMessage: "Bir önceki mesaja cevap vermeyip görüldü attıktan sonra gelen sessizlik.",
      otherPerson: "Flört",
      otherPersonPersonality: "Soğuk ve Mesafeli",
      difficultyReason: "Kırmadan reddetmek istiyorum",
      goal: "Konuşmayı sürdürmek",
      tone: "Esprili",
      replyLength: "Tek cümle",
      preserveRelationship: "Hayır",
      fear: "Rezil olmak veya ısrarcı görünmek",
    },
  },
  {
    id: "pasif-agresif-cevap",
    title: "Pasif-Agresif Mail Duruşu",
    description: "Size imalı ve üstü kapalı suçlayıcı mail yazan yöneticinize profesyonelce cevap verin.",
    category: "zor_mesajlar",
    difficulty: "Orta",
    context: {
      incomingMessage: "Sanırım projenin önemini tam kavrayamadın ya da vaktin yoktu. Yine de eline sağlık.",
      otherPerson: "Patron",
      otherPersonPersonality: "Pasif-Agresif / İğneleyici",
      difficultyReason: "Kendimi savunmak istiyorum",
      goal: "Sınır koymak",
      tone: "Profesyonel",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      fear: "Öfkeyle yanıt verip profesyonel imajımı zedelemek",
    },
  },
  {
    id: "kahve-daveti-reddi",
    title: "Kahve Davetini Kibarca Reddetme",
    description: "İlgi duymadığınız birinin ısrarlı kahve içme teklifini net ama incitmeden geri çevirin.",
    category: "zor_mesajlar",
    difficulty: "Kolay",
    context: {
      incomingMessage: "Bu hafta sonu müsait olunca bir kahve içelim mi, ne dersin?",
      otherPerson: "Tanımadığım biri",
      otherPersonPersonality: "Anlayışlı ve Mantıklı",
      difficultyReason: "Kırmadan reddetmek istiyorum",
      goal: "Reddetmek",
      tone: "Kırmadan ama kararlı",
      replyLength: "Tek cümle",
      preserveRelationship: "Hayır",
      fear: "Karşı tarafın kırılması veya kaba görünmek",
    },
  },
  // --- EĞİTİM / OKUL ---
  {
    id: "grup-arkadasi-kaytarma",
    title: "Çalışmayan Ödev Arkadaşı",
    description: "Grup ödevinde hiçbir işe elini sürmeyen ama adı yazılacak olan arkadaşınızı uyarın.",
    category: "egitim_okul",
    difficulty: "Orta",
    context: {
      incomingMessage: "Kanka ben bu aralar çok yoğunum, slaytları siz halledersiniz değil mi?",
      otherPerson: "Grup Arkadaşı",
      otherPersonPersonality: "Pasif-Agresif / İğneleyici",
      difficultyReason: "Grupta iş bölümü yaptırmak",
      goal: "İş paylaşımı yapmak",
      tone: "Net ve kararlı",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      fear: "Dışlanmak veya kaba görünmek",
      redLine: "Katkı sağlamayanın adını ödeve yazmamak",
    },
  },
  {
    id: "hoca-not-itiraz",
    title: "Hocadan Sınav Notu İtirazı",
    description: "Sınav kağıdınızda bariz bir puanlama hatası olduğunu düşünüp hocadan incelenmesini talep edin.",
    category: "egitim_okul",
    difficulty: "Kolay",
    context: {
      incomingMessage: "Sınav kağıtlarını son derece objektif okudum, itirazı olan resmi dilekçe versin.",
      otherPerson: "Akademisyen / Hoca",
      otherPersonPersonality: "Otoriter ve Sert",
      difficultyReason: "Kağıdın incelenmesini kibarca talep etmek",
      goal: "Kağıdın incelenmesini sağlamak",
      tone: "Profesyonel ve kibar",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      fear: "Hocanın tepkisini çekmek veya notumu daha da düşürmesi",
    },
  },
  // --- GÜNLÜK YAŞAM / KOMŞULUK ---
  {
    id: "gurultucu-ust-komsu",
    title: "Gürültücü Üst Komşu",
    description: "Gece saatlerinde aşırı ses yapan üst komşunuzu uykunuz bölündüğü için kibarca ama net uyarın.",
    category: "gunluk_yasam",
    difficulty: "Zor",
    context: {
      incomingMessage: "Çocuklar koşuyor ne yapalım, apartmanda yaşamanın kuralları bunlar.",
      otherPerson: "Üst Komşu",
      otherPersonPersonality: "Savunmacı ve Israrcı",
      difficultyReason: "Gürültünün kesilmesini istemek",
      goal: "Gürültünün kesilmesini sağlamak",
      tone: "Net ve kararlı",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      fear: "Tartışma çıkması veya düşmanlık beslenmesi",
      redLine: "Saat 23:00'ten sonra gürültünün devam etmesini kabul edemem",
    },
  },
  {
    id: "tesisatci-usta-gecikme",
    title: "İşi Geciktiren Tesisatçı Usta",
    description: "Evdeki sızıntıyı yapmak için gelip yarım bırakan ve günlerdir yalan söyleyen ustaya sınır çizin.",
    category: "gunluk_yasam",
    difficulty: "Orta",
    context: {
      incomingMessage: "Usta diğer şantiyede acil işim çıktı, yarın sabah ilk iş oradayım.",
      otherPerson: "Tesisatçı Usta",
      otherPersonPersonality: "Yoğun ve Dikkatsiz",
      difficultyReason: "İşin bitirilmesi için baskı kurmak",
      goal: "İşin bugün bitirilmesini veya iade almayı sağlamak",
      tone: "Sert ama saygılı",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Sadece işin düzgün bitmesini istiyorum",
      fear: "Ustanın tamamen işi bırakıp kaçması veya agresifleşmesi",
    },
  },
  {
    id: "ik-terfi-beklentisi",
    title: "İK ile Terfi/Unvan Görüşmesi",
    description: "Terfi döneminizin gelmesine rağmen sessiz kalan İK departmanı ile profesyonelce masaya oturun.",
    category: "is_kariyer",
    difficulty: "Zor",
    context: {
      incomingMessage: "Şu anki rolümde 2 yılı geride bıraktım ve üstlendiğim ek sorumluluklarla beraber unvan/kıdem artışı beklentimi paylaşmak istiyorum.",
      otherPerson: "İK (İnsan Kaynakları)",
      otherPersonPersonality: "Otoriter ve Sert",
      difficultyReason: "Terfi ve unvan artışı talep etmek",
      goal: "Kıdem/Unvan artışı almak",
      tone: "Net ve kararlı",
      replyLength: "Detaylı mesaj",
      preserveRelationship: "Evet",
      fear: "Şirkete bağlılığımın sorgulanması veya sürecin askıya alınması",
      otherPersonAttitude: "Pazarlıkçı",
      previouslyDiscussed: "Hayır, ilk kez açılacak",
      redLine: "Aynı unvanla 6 ay daha devam etmeyi kabul edemem"
    }
  },
  {
    id: "burnout-bildirimi",
    title: "Yöneticiden İş Yükü Düzenlemesi",
    description: "Son dönemdeki aşırı iş yükü sebebiyle sağlığınızın etkilendiğini yöneticinize kırmadan ama net şekilde iletin.",
    category: "is_kariyer",
    difficulty: "Orta",
    context: {
      incomingMessage: "Son 3 aydır akşamları ve hafta sonları da çalışmak durumunda kalıyorum. Bu iş yükü sürdürülebilir değil.",
      otherPerson: "Yönetici / Müdür",
      otherPersonPersonality: "Yoğun ve Dikkatsiz",
      difficultyReason: "Tükenmişlik hissini ve iş yükü sınırını açıklamak",
      goal: "İş yükünün azaltılması veya yeni bir görev dağılımı yapılması",
      tone: "Yumuşak ama ciddi",
      replyLength: "Detaylı mesaj",
      preserveRelationship: "Evet",
      fear: "İş stresine dayanıksız veya yetersiz olarak yaftalanmak",
      otherPersonAttitude: "Savunmacı",
      previouslyDiscussed: "Hayır, ilk kez açılacak",
      redLine: "Haftalık 45 saatin üzerindeki fazla mesaileri kabul etmem"
    }
  },
  {
    id: "freelance-sure-talebi",
    title: "Müşteriden Ek Süre İsteme",
    description: "Son dakika çıkan teknik engeller yüzünden geciken teslimatı müşteriyi kaybetmeden erteleme provası yapın.",
    category: "is_kariyer",
    difficulty: "Orta",
    context: {
      incomingMessage: "Entegrasyon aşamasında öngöremediğimiz bir API hatası aldık, projenin teslimini 3 gün ertelemek durumundayız.",
      otherPerson: "Müşteri",
      otherPersonPersonality: "Israrcı ve Zorlayıcı",
      difficultyReason: "Gecikme için haklı bir gerekçe sunup ek süre almak",
      goal: "Müşteri memnuniyetini bozmadan 3 günlük ek süre almak",
      tone: "Profesyonel ve kibar",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      fear: "Güven kaybı yaşamak veya cezai şart uygulanması",
      otherPersonAttitude: "Artışı kabul etmiyor",
      previouslyDiscussed: "Hayır, ilk kez açılacak",
      redLine: "Ekstra indirim veya ücretsiz ek özellik talebini kabul etmem"
    }
  },
  {
    id: "bulusma-reddetme",
    title: "Israrcı Flörtü Kırmadan Reddetme",
    description: "Birkaç kez buluştuğunuz ama kimyanızın uyuşmadığı kişinin tekrar görüşme teklifini saygılı bir şekilde geri çevirin.",
    category: "flort_iliski",
    difficulty: "Kolay",
    context: {
      incomingMessage: "Bu cuma akşamı yine o çok sevdiğin restorana gidelim mi? Seni çok özledim.",
      otherPerson: "Flört",
      relationshipDuration: "Birkaç hafta",
      otherPersonPersonality: "Duygusal ve Hassas",
      otherPersonAttitude: "İlgili ama belirsiz",
      difficultyReason: "Hislerimin uyuşmadığını kırmadan iletmek",
      goal: "İlişkiyi kibarca sonlandırmak",
      tone: "Net ve mesafeli",
      replyLength: "Tek cümle",
      preserveRelationship: "Sadece saygılı kapatmak istiyorum",
      avoidAction: "Umut vermek veya bahaneler üretmek",
      noReplyAction: "Bir daha yazmayacağım",
      fear: "Kaba veya kırıcı görünmek"
    }
  },
  {
    id: "gelecek-beklentisi-iliski",
    title: "Partnerle Gelecek Planı Konuşması",
    description: "Ciddi bir ilişki isterken karşı tarafın anı yaşama odaklı gevşek tavırlarına karşı sınırlarınızı çizin.",
    category: "flort_iliski",
    difficulty: "Zor",
    context: {
      incomingMessage: "İlişkimizin ciddiyeti ve uzun vadeli planlarımız hakkında ne düşündüğünü merak ediyorum.",
      otherPerson: "Sevgili",
      relationshipDuration: "Birkaç ay",
      otherPersonPersonality: "Soğuk ve Mesafeli",
      otherPersonAttitude: "Kararsız",
      difficultyReason: "İlişkinin geleceğini sorgulamak",
      goal: "Karşı tarafın niyetinin ciddi olup olmadığını anlamak",
      tone: "Samimi ve açık",
      replyLength: "Detaylı mesaj",
      preserveRelationship: "Evet",
      avoidAction: "Karşı tarafa evlilik baskısı yapmak",
      noReplyAction: "Mesafe koymak istiyorum",
      fear: "Partnerin bu konuşmadan korkup kaçması"
    }
  },
  {
    id: "sosyal-medya-sinirlari",
    title: "Partnerin Sosyal Medya Kullanımı",
    description: "Partnerinizin sosyal medyadaki bazı etkileşimlerinin sizi rahatsız ettiğini kıskançlık krizine girmeden sakinlikle anlatın.",
    category: "flort_iliski",
    difficulty: "Orta",
    context: {
      incomingMessage: "Eski sevgilinin fotoğraflarını beğenmeye devam etmen beni huzursuz ediyor, bunu konuşabilir miyiz?",
      otherPerson: "Sevgili",
      relationshipDuration: "Birkaç ay",
      otherPersonPersonality: "Pasif-Agresif / İğneleyici",
      otherPersonAttitude: "Savunmacı",
      difficultyReason: "Kıskançlık / saygı sınırlarını belirlemek",
      goal: "Karşılıklı sınırları netleştirmek",
      tone: "Sakin",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      avoidAction: "Öfke patlaması yaşamak veya tehditkar konuşmak",
      noReplyAction: "Bekleyeceğim",
      fear: "Aşırı kısıtlayıcı veya özgüvensiz görünmek"
    }
  },
  {
    id: "ev-arkadasi-temizlik",
    title: "Ev Arkadaşıyla Temizlik Uyarısı",
    description: "Evin ortak alanlarını sürekli dağınık ve kirli bırakan ev arkadaşınızı sertleşmeden uyarın.",
    category: "aile_arkadas",
    difficulty: "Kolay",
    context: {
      incomingMessage: "Ortak alanların temizliği ve bulaşıkların birikmesi konusunda bir düzen oturtmamız gerekiyor.",
      otherPerson: "Ev Arkadaşı",
      closenessLevel: "Yakın ama hassas",
      otherPersonPersonality: "Pasif-Agresif / İğneleyici",
      otherPersonAttitude: "Konuyu değiştirebilir",
      pastConversations: "Genelde tartışmaya dönüyor",
      difficultyReason: "Ortak yaşam kurallarına uymasını istemek",
      goal: "Temizlik nöbeti / düzeni oluşturmak",
      tone: "Sakin ama net",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      fear: "Evde huzursuzluk çıkması veya aşırı titiz damgası yemek"
    }
  },
  {
    id: "koruyucu-ebeveyn-sinir",
    title: "Ebeveynin Müdahalesini Sınırlama",
    description: "Her gün saat kaçta nerede olduğunuzu soran ve kararlarınızı eleştiren ebeveyninize sınırlarınızı çizin.",
    category: "aile_arkadas",
    difficulty: "Orta",
    context: {
      incomingMessage: "Dün gece nerede kaldın? Kiminleydin? Neden telefonlarıma hemen bakmıyorsun?",
      otherPerson: "Anne",
      closenessLevel: "Aile olduğu için kopmak istemiyorum",
      otherPersonPersonality: "Geleneksel / Israrcı",
      otherPersonAttitude: "Suçluluk hissettirebilir",
      pastConversations: "Ben susuyorum",
      difficultyReason: "Ebeveyne karşı bağımsız bir yetişkin olduğunu kanıtlamak",
      goal: "Hayatımla ilgili kararlara saygı duyulmasını sağlamak",
      tone: "Kırmadan sınır koyan",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      fear: "Beni bencil veya vefasız bir evlat olarak görmeleri"
    }
  },
  {
    id: "dedikoducu-arkadas-uyari",
    title: "Sırları Paylaşan Arkadaşı Durdurma",
    description: "Baş başa konuştuğunuz özel bir konuyu başkasından duyduğunuzda, bu güven kırıklığını arkadaşınıza anlatın.",
    category: "aile_arkadas",
    difficulty: "Orta",
    context: {
      incomingMessage: "Sana sadece senin bilmen şartıyla anlattığım konuyu dün akşam ortak grubumuzda başkasından duydum. Çok şaşırdım.",
      otherPerson: "Yakın arkadaş",
      closenessLevel: "Çok yakın",
      otherPersonPersonality: "Alıngan ve Hassas",
      otherPersonAttitude: "Alınabilir",
      pastConversations: "Genelde iyi",
      difficultyReason: "Güven kırıklığını ve duyulan rahatsızlığı iletmek",
      goal: "Güven sınırını tekrar çizmek ve özür almak",
      tone: "Sakin ama net",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      fear: "Arkadaşımın olayı inkar etmesi veya abarttığımı söylemesi"
    }
  },
  {
    id: "ikinci-el-pazarlik",
    title: "İkinci Eşya Pazarlığı",
    description: "Bir platformda beğendiğiniz ürünü bütçenize uydurmak için satıcıyla saygılı bir şekilde pazarlık edin.",
    category: "para_pazarlik",
    difficulty: "Kolay",
    context: {
      incomingMessage: "İlanınızdaki çalışma masasını çok beğendim. Bütçem 2.000 TL, ortada buluşabilir miyiz?",
      otherPerson: "Satıcı",
      otherPersonPersonality: "Para Göz ve Katı",
      financialIssue: "İkinci el alışveriş",
      currentAmount: "3.000 TL",
      minAcceptableLevel: "En fazla 2.300 TL ödeyebilirim",
      otherPersonAttitude: "Artışı kabul etmiyor",
      leverageOrAlternative: "Ürünü elden hemen bugün gelip alabilecek olmam",
      difficultyReason: "Fiyatı bütçeme göre düşürmeye çalışmak",
      goal: "Mümkün olan en düşük fiyata anlaşmak",
      tone: "Uzlaşmacı",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      noAgreementAction: "Alternatif teklif sunarım",
      fear: "Kaba veya ölücü alıcı muamelesi görmek"
    }
  },
  {
    id: "hasarli-urun-iade",
    title: "Satıcıdan Hasarlı Ürün Değişimi",
    description: "Kargo ile kırık gelen pahalı bir ürün için suçu kargoya atan inatçı satıcıya karşı hakkınızı savunun.",
    category: "para_pazarlik",
    difficulty: "Zor",
    context: {
      incomingMessage: "Paketi teslim alırken hasar tespit tutanağı tutturmadıysanız sorumluluk bize ait değildir, kargo şirketiyle görüşün.",
      otherPerson: "E-Ticaret Satıcısı",
      otherPersonPersonality: "Otoriter ve Sert",
      financialIssue: "Ürün iadesi / değişim",
      currentAmount: "8.500 TL",
      minAcceptableLevel: "Hasarlı parçanın ücretsiz olarak yenisiyle değiştirilmesi",
      otherPersonAttitude: "Artışı kabul etmiyor",
      leverageOrAlternative: "Paket açılış videosu ve Tüketici Hakem Heyeti başvuru tehdidi",
      difficultyReason: "Tüketici hakkını sonuna kadar savunmak",
      goal: "Ücretsiz değişim veya tam iade almak",
      tone: "Sert ama saygılı",
      replyLength: "Detaylı mesaj",
      preserveRelationship: "Hayır",
      noAgreementAction: "Masadan kalkarım",
      fear: "Paranın tamamen yanması ve hukuki süreçlerle uğraşmak"
    }
  },
  {
    id: "ortak-tatil-gider-paylasimi",
    title: "Arkadaşla Tatil Gideri Paylaşimi",
    description: "Ortak çıkılan tatilde tüm hesabı sizin kartınızdan ödeyip günlerdir kendi payını göndermeyen arkadaşınızdan parayı isteyin.",
    category: "para_pazarlik",
    difficulty: "Orta",
    context: {
      incomingMessage: "Geçen haftaki tatil otel ve yemek masraflarının dökümünü çıkardım, senin payın 6.200 TL tutuyor.",
      otherPerson: "Yakın arkadaş",
      otherPersonPersonality: "Yoğun ve Dikkatsiz",
      financialIssue: "Tatil masrafı paylaşımı",
      currentAmount: "6.200 TL",
      minAcceptableLevel: "Tutarı bu hafta sonuna kadar eksiksiz göndermesi",
      otherPersonAttitude: "Ödemeyi geciktiriyor",
      leverageOrAlternative: "Aramızda anlaştığımız splitwise/excel dökümü",
      difficultyReason: "Yakın arkadaştan para istemenin getirdiği çekince",
      goal: "Paranın tamamının ödenmesini sağlamak",
      tone: "Kırmadan sınır koyan",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      noAgreementAction: "Süre isterim",
      fear: "Arkadaşımın parayı önemsemediğimi veya cimri olduğumu düşünmesi"
    }
  },
  {
    id: "is-teklifi-kibar-red",
    title: "Gelen İş Teklifini Kibarca Reddetme",
    description: "Mülakatlarını geçtiğiniz ama şartları uymadığı için reddetmek zorunda kaldığınız firmaya profesyonel bir dönüş yapın.",
    category: "zor_mesajlar",
    difficulty: "Kolay",
    context: {
      incomingMessage: "Tüm aşamaları başarıyla tamamladınız. Sizi aramızda görmek istiyoruz, teklifimizi ekte iletiyorum.",
      otherPerson: "İK (İnsan Kaynakları)",
      otherPersonPersonality: "Anlayışlı ve Mantıklı",
      difficultyReason: "Gelen teklifi profesyonelce geri çevirmek",
      goal: "Gelecekteki fırsatlar için kapıyı açık bırakarak reddetmek",
      tone: "Profesyonel ve kibar",
      replyLength: "Detaylı mesaj",
      preserveRelationship: "Evet",
      fear: "İK uzmanını kızdırmak veya kara listeye alınmak"
    }
  },
  {
    id: "yanlis-mesaj-kurtarma",
    title: "Yanlışlıkla Gönderilen Mesajı Toparlama",
    description: "Hakkında eleştirel konuştuğunuz arkadaşınıza yanlışlıkla gönderdiğiniz mesajı durumu batırmadan toparlayın.",
    category: "zor_mesajlar",
    difficulty: "Zor",
    context: {
      incomingMessage: "Bu ne biçim bir mesaj? Benim hakkımda böyle mi düşünüyordun gerçekten?",
      otherPerson: "Yakın arkadaş",
      otherPersonPersonality: "Duygusal ve Hassas",
      difficultyReason: "Hatamı kabul edip dürüstçe durumu kurtarmak",
      goal: "Arkadaşımı kaybetmeden durumu açıklamak ve özür dilemek",
      tone: "Samimi ve açık",
      replyLength: "Detaylı mesaj",
      preserveRelationship: "Evet",
      fear: "Arkadaşlığın tamamen bitmesi ve grupta dışlanmak"
    }
  },
  {
    id: "danisman-tez-inceleme",
    title: "Tez Danışmanına Hatırlatma Maili",
    description: "Haftalardır tezinizin taslağını incelemeyen ve mezuniyetinizi tehlikeye atan hocanıza saygılı ama net bir mail yazın.",
    category: "egitim_okul",
    difficulty: "Orta",
    context: {
      incomingMessage: "Hocam, teslim ettiğim tez taslağı üzerindeki düzeltmelerinizi alabilirsem son düzenlemeleri yapacağım.",
      otherPerson: "Akademisyen / Hoca",
      otherPersonPersonality: "Otoriter ve Sert",
      difficultyReason: "Hocayı sıkıştırmadan tezi okumasını rica etmek",
      goal: "Tez geri bildirimini en geç haftaya kadar almak",
      tone: "Profesyonel ve kibar",
      replyLength: "Detaylı mesaj",
      preserveRelationship: "Evet",
      fear: "Hocanın sinirlenip teslim tarihini daha da ertelemesi"
    }
  },
  {
    id: "grup-odevi-liderlik",
    title: "Ekibi Çalışmaya Teşvik Etme",
    description: "Teslim tarihine 3 gün kalmasına rağmen gruptan kimsenin bir şey yazmadığı ödev grubunu motive edip harekete geçirin.",
    category: "egitim_okul",
    difficulty: "Kolay",
    context: {
      incomingMessage: "Arkadaşlar merhaba, ödev teslimine 3 gün kaldı. Herkes kendi bölümünü ne zaman tamamlayabilir?",
      otherPerson: "Sınıf Arkadaşları",
      otherPersonPersonality: "Yoğun ve Dikkatsiz",
      difficultyReason: "Gruptaki tembelliği kırıp iş bölümü yaptırmak",
      goal: "Görev paylaşımı yapıp herkesin işe başlamasını sağlamak",
      tone: "Net ve kararlı",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      fear: "Grupta uyumsuz veya patronluk taslayan biri gibi görünmek"
    }
  },
  {
    id: "hoca-referans-mektubu",
    title: "Hocadan Referans Mektubu İsteme",
    description: "Yurt dışı yüksek lisans başvurusu için dersinde başarılı olduğunuz hocadan referans rica edin.",
    category: "egitim_okul",
    difficulty: "Kolay",
    context: {
      incomingMessage: "Sayın Hocam, dersinizden aldığım başarı doğrultusunda yüksek lisans başvurum için referans mektubu rica edebilir miyim?",
      otherPerson: "Akademisyen / Hoca",
      otherPersonPersonality: "Anlayışlı ve Mantıklı",
      difficultyReason: "Hocadan akademik destek talep etmek",
      goal: "Hocanın referans mektubu yazmayı kabul etmesi",
      tone: "Profesyonel ve kibar",
      replyLength: "Detaylı mesaj",
      preserveRelationship: "Evet",
      fear: "Hocanın beni yeterince tanımadığını söyleyip reddetmesi"
    }
  },
  {
    id: "apartman-park-kavgasi",
    title: "Park Yerinizi İşgal Eden Komşu",
    description: "Apartman otoparkında size tahsis edilen alana arabasını sürekli çeken komşunuzla tartışmadan sorunu çözün.",
    category: "gunluk_yasam",
    difficulty: "Orta",
    context: {
      incomingMessage: "Komşu selam, benim otopark numaram olan 12 numaralı yere aracını çekmişsin sanırım, çıkmam gerekiyor.",
      otherPerson: "Komşu",
      otherPersonPersonality: "Savunmacı ve Israrcı",
      difficultyReason: "Komşuluk ilişkilerini bozmadan hakkımı savunmak",
      goal: "Aracını hemen çekmesini ve bir daha park etmemesini sağlamak",
      tone: "Net ve kararlı",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      fear: "Apartman içinde kavga çıkması veya arabama zarar verilmesi",
      redLine: "Sadece 5 dakikalığına bile olsa yerimin işgal edilmesini kabul edemem"
    }
  },
  {
    id: "kurye-paket-teslim-sikayet",
    title: "Kargoyu Kapıya Getirmeyen Kurye",
    description: "Evde olmanıza rağmen 'adreste bulunamadı' diye not düşüp paketi şubeye bırakan kargo kuryesiyle yüzleşin.",
    category: "gunluk_yasam",
    difficulty: "Orta",
    context: {
      incomingMessage: "Geldik ama zilinize bastık açan olmadı, paketinizi en yakın şubemizden alabilirsiniz.",
      otherPerson: "Kargo Kuryesi",
      otherPersonPersonality: "Yoğun ve Dikkatsiz",
      difficultyReason: "Evde olduğumu kanıtlayıp paketi kapıma getirtmek",
      goal: "Kuryenin paketi bugün tekrar adresime teslim etmesini sağlamak",
      tone: "Net ve kararlı",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Hayır",
      fear: "Kuryenin agresif davranması veya şikayetimin sonuçsuz kalması"
    }
  },
  {
    id: "internet-ariza-destek",
    title: "Müşteri Temsilcisine Altyapı Şikayeti",
    description: "Günlerdir interneti kesik olan ve sürekli otomatik yanıtlarla sizi oyalayan müşteri hizmetleriyle görüşün.",
    category: "gunluk_yasam",
    difficulty: "Orta",
    context: {
      incomingMessage: "Bölgenizde genel bir çalışma bulunmaktadır. Kesintinin ne zaman düzeleceği henüz belli değildir.",
      otherPerson: "Müşteri Temsilcisi",
      otherPersonPersonality: "Yoğun ve Dikkatsiz",
      difficultyReason: "Sorunu üst mercilere taşıyıp somut bir çözüm tarihi almak",
      goal: "Teknik ekibin yönlendirilmesini sağlamak veya fatura indirimi almak",
      tone: "Sert ama saygılı",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Hayır",
      fear: "İnternetin günlerce gelmemesi ve işlerimin aksaması"
    }
  },
  {
    id: "is-karsi-teklif-pazarlik",
    title: "Şirketle Karşı Teklif Pazarlığı",
    description: "Başka bir firmadan aldığınız yüksek teklifi mevcut şirketinize ileterek şartlarınızı iyileştirmelerini isteyin.",
    category: "is_kariyer",
    difficulty: "Zor",
    context: {
      incomingMessage: "Başka bir firmadan aldığım teklif, mevcut şartlarımın oldukça üzerinde. Şirkette kalabilmem için teklifimi değerlendirebilir misiniz?",
      otherPerson: "Yönetici / Müdür",
      otherPersonPersonality: "Anlayışlı ve Mantıklı",
      difficultyReason: "Mevcut şirketle kalmak için pazarlık yapmak",
      goal: "Mevcut şirketten karşı teklif (zam/unvan) koparmak",
      tone: "Profesyonel ve kibar",
      replyLength: "Detaylı mesaj",
      preserveRelationship: "Evet",
      fear: "Sadakatsizlikle suçlanmak veya mevcut teklifi kaybetmek",
      otherPersonAttitude: "Pazarlıkçı",
      previouslyDiscussed: "Hayır, ilk kez açılacak",
      redLine: "Teklif edilen yeni maaşın altındaki hiçbir iyileştirmeyi kabul etmem"
    }
  },
  {
    id: "mentorluk-talebi-ust-yonetici",
    title: "Yöneticiden Mentorluk İsteme",
    description: "Şirketteki vizyoner bir liderden kariyer gelişiminiz için resmi olmayan mentorluk talep edin.",
    category: "is_kariyer",
    difficulty: "Kolay",
    context: {
      incomingMessage: "Kariyer hedeflerim doğrultusunda sizin deneyimlerinizden yararlanmak ve ayda bir kez kahve eşliğinde görüşmek isterim.",
      otherPerson: "Yönetici / Müdür",
      otherPersonPersonality: "Anlayışlı ve Mantıklı",
      difficultyReason: "Liderden mentorluk rica etmek",
      goal: "Mentorluk teklifini kabul ettirmek",
      tone: "Profesyonel ve kibar",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      fear: "Yoğun programından dolayı reddedilmek",
      otherPersonAttitude: "Anlayışlı",
      previouslyDiscussed: "Hayır, ilk kez açılacak",
      redLine: "Israrcı veya saygısız görünmek istemem"
    }
  },
  {
    id: "rakip-firmaya-gecis",
    title: "Rakip Firmaya Geçiş Açıklaması",
    description: "Rakip bir firmadan gelen çok cazip teklifi kabul ettiniz. Yöneticinize durumu kırmadan açıklayın.",
    category: "is_kariyer",
    difficulty: "Zor",
    context: {
      incomingMessage: "Kariyerimde yeni bir fırsat olarak rakip bir firmada başlayacağımı bildirmek istiyorum.",
      otherPerson: "Yönetici / Müdür",
      otherPersonPersonality: "Otoriter ve Sert",
      difficultyReason: "İstifa etmek / rakibe geçişi açıklamak",
      goal: "Köprüleri yakmadan ihbar süresini başlatmak",
      tone: "Profesyonel ve kibar",
      replyLength: "Detaylı mesaj",
      preserveRelationship: "Sadece saygılı kapatmak istiyorum",
      fear: "Proje bilgilerini sızdırmakla suçlanmak veya kötü ayrılmak",
      otherPersonAttitude: "Savunmacı",
      previouslyDiscussed: "Hayır, ilk kez açılacak",
      redLine: "İhbar sürem dolmadan hemen ayrılmaya zorlanmayı kabul etmem"
    }
  },
  {
    id: "bulusma-sonrasi-sogukluk",
    title: "İlk Buluşma Sonrası Netlik",
    description: "Çok iyi geçen bir ilk buluşma sonrasında aniden mesafeli davranmaya başlayan kişiye durumu açıkça sorun.",
    category: "flort_iliski",
    difficulty: "Orta",
    context: {
      incomingMessage: "Buluşmamızın ardından iletişimimiz biraz soğudu gibi hissettim, her şey yolunda mı?",
      otherPerson: "Flört",
      relationshipDuration: "Birkaç hafta",
      otherPersonPersonality: "Soğuk ve Mesafeli",
      otherPersonAttitude: "Kararsız",
      difficultyReason: "Soğuk davranılmasının nedenini öğrenmek",
      goal: "Aramızdaki durumun netleşmesini sağlamak",
      tone: "Samimi ve açık",
      replyLength: "Tek cümle",
      preserveRelationship: "Emin değilim",
      avoidAction: "Sitem etmek veya trip atmak",
      noReplyAction: "Bir daha yazmayacağım",
      fear: "Aşırı ilgi gösterip muhtaç görünmek"
    }
  },
  {
    id: "birlikte-yasama-teklifi",
    title: "Partnere Birlikte Yaşama Teklifi",
    description: "İlişkinizde bir sonraki adıma geçmek ve aynı eve çıkmak istediğinizi partnerinize baskı yapmadan önerin.",
    category: "flort_iliski",
    difficulty: "Orta",
    context: {
      incomingMessage: "İlişkimizin gidişatı doğrultusunda artık aynı evi paylaşma zamanımızın geldiğini düşünüyorum.",
      otherPerson: "Sevgili",
      relationshipDuration: "Çok uzun süre",
      otherPersonPersonality: "Duygusal ve Hassas",
      otherPersonAttitude: "Kararsız",
      difficultyReason: "Ciddi bir gelecek adımı önermek",
      goal: "Birlikte yaşama konusunda fikrini almak",
      tone: "Samimi ve açık",
      replyLength: "Detaylı mesaj",
      preserveRelationship: "Evet",
      avoidAction: "Acele ettirmek veya maddi baskı kurmak",
      noReplyAction: "Bekleyeceğim",
      fear: "Hazır olmadığını söyleyip reddetmesi"
    }
  },
  {
    id: "iliski-alan-ihtiyaci",
    title: "Partnerden Alan Talep Etme",
    description: "Sürekli dip dibe olmaktan bunaldınız. Partnerinize onu sevdiğinizi ama kendinize zaman ayırmak istediğinizi iletin.",
    category: "flort_iliski",
    difficulty: "Orta",
    context: {
      incomingMessage: "Seni çok seviyorum ama hafta sonlarında biraz kendime ve hobilerime vakit ayırmaya ihtiyacım var.",
      otherPerson: "Sevgili",
      relationshipDuration: "Çok uzun süre",
      otherPersonPersonality: "Duygusal ve Hassas",
      otherPersonAttitude: "Alıngan ve Hassas",
      difficultyReason: "İlişkide bireysel alan talep etmek",
      goal: "Haftada en az bir günü kendime ayırmak konusunda anlaşmak",
      tone: "Sakin",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      avoidAction: "Sevgisizlik olarak algılanmasına izin vermek",
      noReplyAction: "Bekleyeceğim",
      fear: "Partnerin kendisini değersiz hissetmesi veya küsmesi"
    }
  },
  {
    id: "arkadas-surekli-gec-kalma",
    title: "Sürekli Geç Kalan Arkadaş",
    description: "Buluşma saatlerine asla uymayan ve sizi her defasında bekleten arkadaşınızla bu durumu konuşun.",
    category: "aile_arkadas",
    difficulty: "Kolay",
    context: {
      incomingMessage: "Ya kanka yine 30 dakika gecikeceğim, trafik çok fena, kusura bakma.",
      otherPerson: "Yakın arkadaş",
      closenessLevel: "Çok yakın",
      otherPersonPersonality: "Yoğun ve Dikkatsiz",
      otherPersonAttitude: "Anlayışlı olabilir",
      pastConversations: "Genelde iyi",
      difficultyReason: "Zamanıma saygı duyulmadığını belirtmek",
      goal: "Geç kalma huyunu düzeltmesini istemek",
      tone: "Sakin ama net",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      fear: "Ufak bir konuyu büyütiyormuş gibi görünmek"
    }
  },
  {
    id: "dugun-daveti-reddi",
    title: "Yakın Arkadaşın Düğününü Reddetme",
    description: "Maddi veya kişisel sebeplerle çok yakın bir arkadaşınızın şehir dışındaki düğününe gidemeyeceğinizi açıklayın.",
    category: "aile_arkadas",
    difficulty: "Orta",
    context: {
      incomingMessage: "Gelecek ayki düğünüme mutlaka bekliyorum, sensiz bir düğün düşünemiyorum kanka.",
      otherPerson: "Yakın arkadaş",
      closenessLevel: "Çok yakın",
      otherPersonPersonality: "Duygusal ve Hassas",
      otherPersonAttitude: "Alınabilir",
      pastConversations: "Genelde iyi",
      difficultyReason: "Düğüne katılamayacağımı kırıp dökmeden anlatmak",
      goal: "Maddi/kişisel engeli açıklayıp anlayış göstermesini sağlamak",
      tone: "Çok yumuşak",
      replyLength: "Detaylı mesaj",
      preserveRelationship: "Evet",
      fear: "Arkadaşlığımızın tamamen bitmesi veya dışlanmak"
    }
  },
  {
    id: "kardesler-arasi-paylasim",
    title: "Kardeşle Sınır / Eşya Tartışması",
    description: "İzniniz olmadan eşyalarınızı alan veya odanıza müdahale eden kardeşinize sınırlarınızı belirleyin.",
    category: "aile_arkadas",
    difficulty: "Kolay",
    context: {
      incomingMessage: "Senin o ceketini giydim bugün, ne olacak ki altı üstü bir ceket, neden bu kadar abartıyorsun?",
      otherPerson: "Kardeş",
      closenessLevel: "Çok yakın",
      otherPersonPersonality: "Pasif-Agresif",
      otherPersonAttitude: "Konuyu değiştirebilir",
      pastConversations: "Genelde tartışmaya dönüyor",
      difficultyReason: "Kişisel eşyalarıma ve alanıma saygı duyulmasını istemek",
      goal: "İzin istemeden eşyalarımı almamasını kabul ettirmek",
      tone: "Net ve kararlı",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      fear: "Ev içinde gereksiz gerilim veya kavga çıkması"
    }
  },
  {
    id: "arac-alim-pazarlik",
    title: "Sahibinden Araç Pazarlığı",
    description: "Beğendiğiniz otomobil için telefonda satıcıyla bütçenize göre mantıklı bir pazarlık yürütün.",
    category: "para_pazarlik",
    difficulty: "Orta",
    context: {
      incomingMessage: "Aracım hatasız, boyasızdır. Son fiyatım ilanda yazandır, pazarlık teklif etmeyin lütfen.",
      otherPerson: "Satıcı",
      otherPersonPersonality: "Para Göz ve Katı",
      financialIssue: "Araç alımı",
      currentAmount: "650.000 TL",
      minAcceptableLevel: "En fazla 630.000 TL ödeyebilirim",
      otherPersonAttitude: "Artışı kabul etmiyor",
      leverageOrAlternative: "Nakit olarak hemen bugün notere gidebilecek olmam",
      difficultyReason: "Satıcının katı tutumunu kırıp indirim almak",
      goal: "Fiyatı 630.000 TL seviyesine çekmek",
      tone: "Uzlaşmacı",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      noAgreementAction: "Alternatif teklif sunarım",
      fear: "Satıcının telefonu yüzüme kapatması veya aracı başkasına satması"
    }
  },
  {
    id: "hizmet-abonelik-iptali",
    title: "Spor Salonu Üyelik İptali",
    description: "Taahhüt süresi dolmadan taşınma sebebiyle üyeliğinizi iptal ettirip cayma bedeli ödememeyi müzakere edin.",
    category: "para_pazarlik",
    difficulty: "Orta",
    context: {
      incomingMessage: "Sözleşmeniz gereği 12 aylık taahhüdünüz devam ediyor. İptal durumunda 4.000 TL cayma bedeli yansıtılacaktır.",
      otherPerson: "Müşteri Hizmetleri",
      otherPersonPersonality: "Otoriter ve Sert",
      financialIssue: "Abonelik iptali",
      currentAmount: "4.000 TL",
      minAcceptableLevel: "Cayma bedeli ödemeden veya cüzi bir tutarla iptal etmek",
      otherPersonAttitude: "Artışı kabul etmiyor",
      leverageOrAlternative: "Tüketici Kanunu'ndaki ikametgah değişikliği maddesi",
      difficultyReason: "Hukuki hakkımı arayarak cayma bedelini reddetmek",
      goal: "Ücretsiz üyelik iptali sağlamak",
      tone: "Sert ama saygılı",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Hayır",
      noAgreementAction: "Masadan kalkarım",
      fear: "İcra takibi başlatılması veya haksız bedeli ödemek zorunda kalmak"
    }
  },
  {
    id: "grup-hediye-butce-tartismasi",
    title: "Ortak Hediye Bütçesi İtirazı",
    description: "Arkadaş grubunun ortak arkadaş için belirlediği fahiş hediye bütçesine durumunuzun elvermediğini söyleyerek itiraz edin.",
    category: "para_pazarlik",
    difficulty: "Kolay",
    context: {
      incomingMessage: "Arkadaşlar Ahmet'in doğum günü için kişi başı 3.000 TL topluyoruz, herkes IBAN'a göndersin.",
      otherPerson: "Grup Lideri Arkadaş",
      otherPersonPersonality: "Alıngan ve Hassas",
      financialIssue: "Grup masrafı",
      currentAmount: "3.000 TL",
      minAcceptableLevel: "Kişi başı bütçenin en fazla 1.000 TL olarak güncellenmesi",
      otherPersonAttitude: "Pahalı buluyor",
      leverageOrAlternative: "Maddi olarak şu ara sıkışık olmam",
      difficultyReason: "Maddi durumumu gruba açıklama çekincesi",
      goal: "Bütçeyi düşürmek veya gruptan ayrı hediye almak",
      tone: "Uzlaşmacı",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      noAgreementAction: "Alternatif teklif sunarım",
      fear: "Gruba karşı cimri veya fakir görünmek"
    }
  },
  {
    id: "davetsiz-misafir-reddi",
    title: "Yatılı Kalmak İsteyen Misafiri Reddetme",
    description: "Haftaya İstanbul'a geleceğim de, otellere para vermeyeyim diyorum. Sizde 3-4 gün kalabilir miyim?",
    category: "zor_mesajlar",
    difficulty: "Orta",
    context: {
      incomingMessage: "Haftaya İstanbul'a geleceğim de, otellere para vermeyeyim diyorum. Sizde 3-4 gün kalabilir miyim?",
      otherPerson: "Uzak Akraba / Tanıdık",
      otherPersonPersonality: "Geleneksel / Israrcı",
      difficultyReason: "Akraba ilişkilerini bozmadan hayır diyebilmek",
      goal: "Yatılı kalma talebini kibarca geri çevirmek",
      tone: "Kırmadan ama kararlı",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      fear: "Akraba çevresinde misafir sevmeyen biri olarak konuşulmak"
    }
  },
  {
    id: "arkadas-borc-talebi-red",
    title: "Borç İsteyen Arkadaşı Reddetme",
    description: "Sürekli maddi olarak sıkışan ve geri ödemeleri düzgün yapmayan arkadaşınızın yeni borç talebini geri çevirin.",
    category: "zor_mesajlar",
    difficulty: "Orta",
    context: {
      incomingMessage: "Kanka çok acil 15 bin TL lazım, maaşı alınca hemen göndereceğim söz.",
      otherPerson: "Arkadaş",
      otherPersonPersonality: "Alıngan ve Hassas",
      difficultyReason: "Para ilişkisinin arkadaşlığı bozacağını söyleyerek reddetmek",
      goal: "Borç vermeyi kibarca ama kesin olarak reddetmek",
      tone: "Net ve mesafeli",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      fear: "Arkadaşımın dar gününde yanında olmadığımı düşünüp küsmesi"
    }
  },
  {
    id: "ogrenci-isleri-burs-kesintisi",
    title: "Burs Kesintisine İtiraz Görüşmesi",
    description: "Hak etmediğinizi düşündüğünüz bir yönetmelik maddesi yüzünden kesilen bursunuzun iadesi için memurla görüşün.",
    category: "egitim_okul",
    difficulty: "Orta",
    context: {
      incomingMessage: "Yönetmelik gereği alttan iki dersiniz olduğu için bursunuz otomatik olarak kesilmiştir.",
      otherPerson: "Öğrenci İşleri Memuru",
      otherPersonPersonality: "Otoriter ve Sert",
      difficultyReason: "Memurun bürokratik duvarını aşıp dilekçeyi işleme koydurmak",
      goal: "Bursun tekrar bağlanması için komisyona sevk edilmesini sağlamak",
      tone: "Profesyonel ve kibar",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      fear: "Sert bir yanıt alıp kapı dışarı edilmek"
    }
  },
  {
    id: "hoca-proje-ek-sure",
    title: "Hocadan Ödev/Proje Ek Süresi İsteme",
    description: "Sağlık veya teknik sorunlar sebebiyle yetiştiremediğiniz dönem projesi için hocadan ek süre talep edin.",
    category: "egitim_okul",
    difficulty: "Kolay",
    context: {
      incomingMessage: "Hocam, bilgisayarımın bozulması ve sağlık raporum nedeniyle projeyi teslim tarihine yetiştiremedim. 2 gün ek süre verebilir misiniz?",
      otherPerson: "Akademisyen / Hoca",
      otherPersonPersonality: "Otoriter ve Sert",
      difficultyReason: "Hocayı mazeretimin geçerli olduğuna inandırmak",
      goal: "Not kırılmadan 2 günlük ek teslim süresi almak",
      tone: "Profesyonel ve kibar",
      replyLength: "Detaylı mesaj",
      preserveRelationship: "Evet",
      fear: "Tembellik veya sorumsuzlukla suçlanıp sıfır almak"
    }
  },
  {
    id: "veli-ogretmen-sinir-cizme",
    title: "Velinin Öğretmene Ders Notu Baskısı",
    description: "Çocuğunun notlarının düşük olmasını öğretmen olarak size yükleyen agresif veliyi sakinleştirip durumu açıklayın.",
    category: "egitim_okul",
    difficulty: "Zor",
    context: {
      incomingMessage: "Benim çocuğum evde sürekli çalışıyor, sizin dersinizden nasıl 40 alır? Sınavları çok zor soruyorsunuz.",
      otherPerson: "Öğrenci Velisi",
      otherPersonPersonality: "Savunmacı ve Israrcı",
      difficultyReason: "Veliyi sakinleştirip çocuğun dersteki eksiklerini anlatmak",
      goal: "Notu değiştirmeyeceğimi kabul ettirip ortak çalışma planı yapmak",
      tone: "Profesyonel ve kibar",
      replyLength: "Detaylı mesaj",
      preserveRelationship: "Evet",
      fear: "Velinin okul yönetimine gidip hakkımda şikayette bulunması"
    }
  },
  {
    id: "apartman-yonetici-aidat-israfi",
    title: "Apartman Yöneticisine Aidat İtirazı",
    description: "Yapılmayan hizmetlere rağmen sürekli artan aidatlar hakkında apartman yöneticisiyle sertleşmeden hesap sorun.",
    category: "gunluk_yasam",
    difficulty: "Orta",
    context: {
      incomingMessage: "Apartmanın asansör bakımı ve dış cephe boyası için aidatları bu ay 1.500 TL'den 2.500 TL'ye çıkardık.",
      otherPerson: "Apartman Yöneticisi",
      otherPersonPersonality: "Otoriter ve Sert",
      difficultyReason: "Gereksiz masrafları sorgulamak ve şeffaflık istemek",
      goal: "Gider dökümlerini resmi olarak talep edip bütçe revizyonu istemek",
      tone: "Net ve kararlı",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      fear: "Apartman toplantısında komşularla karşı karşıya gelmek"
    }
  },
  {
    id: "komsuluk-evcil-hayvan-gerginligi",
    title: "Ortak Bahçede Evcil Hayvan Sorunu",
    description: "Bahçede köpeğini tasmasız gezdiren ve çocukları korkutan komşunuzu kibarca uyarın.",
    category: "gunluk_yasam",
    difficulty: "Kolay",
    context: {
      incomingMessage: "Benim köpeğim kimseye zarar vermez, aşırı uysaldır. Neden bu kadar korkuyorsunuz anlamıyorum.",
      otherPerson: "Komşu",
      otherPersonPersonality: "Savunmacı ve Israrcı",
      difficultyReason: "Komşuluk hukukunu gözeterek kuralları hatırlatmak",
      goal: "Köpeğini ortak alanlarda tasmalı gezdirmesini sağlamak",
      tone: "Sakin ama net",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Evet",
      fear: "Komşuyla düşman olmak veya hayvan düşmanı olarak etiketlenmek"
    }
  },
  {
    id: "restoran-hatali-hesap-itiraz",
    title: "Garsona Hatalı Hesap İtirazı",
    description: "Masaya gelmeyen ekstra mezelerin/içeceklerin eklendiği hesaba karşı garsonla veya müdürle konuşun.",
    category: "gunluk_yasam",
    difficulty: "Kolay",
    context: {
      incomingMessage: "Bizde kuver ve sipariş sistemi otomatik işliyor efendim. Masanıza o mezeler mutlaka servis edilmiştir.",
      otherPerson: "Restoran Şefi / Garson",
      otherPersonPersonality: "Otoriter ve Sert",
      difficultyReason: "Hizmet almadığım şeyin parasını ödemeyi reddetmek",
      goal: "Hesabın düzeltilmesini ve kuver/servis ücretinin düşülmesini sağlamak",
      tone: "Net ve kararlı",
      replyLength: "Kısa mesaj",
      preserveRelationship: "Hayır",
      fear: "Mekanda kavga çıkması veya masadakilere karşı mahcup olmak"
    }
  }
];
